spring.application.name=Rest-Api-mit-Spring-AI-MCP
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=hf.co/unsloth/gemma-4-12b-it-GGUF:Q4_K_M
server.port=8081
raumzeit.api.token=${RAUMZEIT_BEARER_TOKEN}
raumzeit.baseurl=https://raumzeit.hka-iwi.de
spring.ai.ollama.embedding.model=nomic-embed-text