spring.application.name=Rest-Api-mit-Spring-AI-MCP
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=qwen3.5
server.port=8081
raumzeit.api.token=${RAUMZEIT_BEARER_TOKEN}
raumzeit.baseurl=https://raumzeit.hka-iwi.de